version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - DJANGO_SETTINGS_MODULE=devops_buddy.settings
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
